-- ============================================================
-- NEURO-AI PARALLELS DATABASE
-- Phase 3a: DML - INSERT DATA (Part 1 of 2)
-- Run this block FIRST, then run phase5_insert_continuation.sql
-- Add SET DEFINE OFF at the top to prevent & substitution errors
-- ============================================================
SET DEFINE OFF;


-- ============================================================
-- STEP 1: FUNCTIONAL_CATEGORY (6 rows)
-- ============================================================
INSERT INTO functional_category (category_name, description) VALUES ('Perception & Encoding','How biological and artificial systems transform raw sensory input into structured internal representations.');
INSERT INTO functional_category (category_name, description) VALUES ('Attention & Selectivity','Mechanisms by which biological and artificial systems selectively focus computational resources on relevant information.');
INSERT INTO functional_category (category_name, description) VALUES ('Memory & Storage','How information is retained, consolidated, and retrieved across short and long timescales in brains and networks.');
INSERT INTO functional_category (category_name, description) VALUES ('Learning & Adaptation','The synaptic and algorithmic rules by which biological and artificial systems update their internal parameters from experience.');
INSERT INTO functional_category (category_name, description) VALUES ('Decision & Prediction','How brains and models compute expectations, evaluate outcomes, and select actions under uncertainty.');
INSERT INTO functional_category (category_name, description) VALUES ('Output & Generation','How biological motor systems and artificial generative models produce structured sequential outputs.');


-- ============================================================
-- STEP 2: BIOLOGICAL_STRUCTURE (16 rows)
-- ============================================================
INSERT INTO biological_structure (bio_name, bio_type, description, brain_location) VALUES ('Primary Visual Cortex (V1)','Brain Region','The first cortical region to process visual information. Contains simple and complex cells with oriented receptive fields that detect edges, spatial frequencies, and orientations.','Occipital lobe');
INSERT INTO biological_structure (bio_name, bio_type, description, brain_location) VALUES ('Inferior Temporal Cortex (IT)','Brain Region','The apex of the ventral visual stream, encoding high-level object representations invariant to position, size, and viewpoint.','Temporal lobe');
INSERT INTO biological_structure (bio_name, bio_type, description, brain_location) VALUES ('Ventral Visual Stream','Neural Circuit','A hierarchical sequence of cortical areas (V1 to V2 to V4 to IT) that progressively transforms pixel-level input into abstract object representations used for recognition.','Occipital to temporal lobe');
INSERT INTO biological_structure (bio_name, bio_type, description, brain_location) VALUES ('Sparse Coding in V1','Cognitive Mechanism','The empirically observed tendency of V1 neurons to respond selectively to specific stimuli with only a small fraction active at any time, maximizing information transmission efficiency.','Occipital lobe');
INSERT INTO biological_structure (bio_name, bio_type, description, brain_location) VALUES ('Hippocampus','Brain Region','Critical for encoding new episodic and declarative memories. Operates as a fast-learning system that indexes neocortical memory traces and supports memory consolidation during sleep.','Medial temporal lobe');
INSERT INTO biological_structure (bio_name, bio_type, description, brain_location) VALUES ('Sleep Replay (REM/NREM)','Cognitive Mechanism','During sleep, neural activity patterns from recent experiences are replayed in compressed form. This consolidates memories from hippocampus to neocortex and prevents interference between memories.','Hippocampus and Neocortex');
INSERT INTO biological_structure (bio_name, bio_type, description, brain_location) VALUES ('Neocortex','Brain Region','The slow-learning long-term memory system. Organized in cortical columns and layers; gradually consolidates knowledge from the hippocampus through repeated replay.','Cerebral cortex');
INSERT INTO biological_structure (bio_name, bio_type, description, brain_location) VALUES ('Synaptic Plasticity (STDP)','Cellular Process','Spike-timing-dependent plasticity: synaptic weights change based on the precise timing difference between pre- and post-synaptic firing. The biological implementation of Hebbian learning.','Cortex and hippocampus');
INSERT INTO biological_structure (bio_name, bio_type, description, brain_location) VALUES ('Hebbian Learning','Cellular Process','The principle that neurons that fire together wire together. Synapses strengthen when pre- and post-synaptic neurons are co-active. The foundational biological learning rule.','Cortex-wide');
INSERT INTO biological_structure (bio_name, bio_type, description, brain_location) VALUES ('Prefrontal Cortex (PFC)','Brain Region','Orchestrates executive function, working memory, and top-down attentional control. Selects which information from posterior cortices receives processing priority.','Frontal lobe');
INSERT INTO biological_structure (bio_name, bio_type, description, brain_location) VALUES ('Cortico-Thalamic Circuit','Neural Circuit','Reciprocal loops between cortex and thalamus that implement gating of sensory information and regulation of attention across the cortex through parallel functional channels.','Cortex and thalamus');
INSERT INTO biological_structure (bio_name, bio_type, description, brain_location) VALUES ('Parietal Cortex','Brain Region','Integrates sensory information with spatial and context signals. Works with PFC to implement exogenous attention and spatial working memory.','Parietal lobe');
INSERT INTO biological_structure (bio_name, bio_type, description, brain_location) VALUES ('Dopaminergic System','Neurotransmitter System','Midbrain dopamine neurons signal reward prediction errors: firing when reward exceeds expectation and pausing when reward is omitted. A biological teaching signal for reinforcement learning.','Midbrain VTA and substantia nigra');
INSERT INTO biological_structure (bio_name, bio_type, description, brain_location) VALUES ('Basal Ganglia','Brain Region','A subcortical network involved in action selection, reward-based learning, and habit formation. Receives dopaminergic prediction error signals and updates action values accordingly.','Subcortical nuclei');
INSERT INTO biological_structure (bio_name, bio_type, description, brain_location) VALUES ('Primary Motor Cortex (M1)','Brain Region','Generates sequential motor commands for voluntary movement. Population-level dynamics encode both movement preparation and execution as trajectories through a high-dimensional state space.','Frontal lobe');
INSERT INTO biological_structure (bio_name, bio_type, description, brain_location) VALUES ('Predictive Coding Hierarchy','Cognitive Mechanism','A theory of cortical computation in which each level predicts the activity of the level below, sending only prediction errors upward. Minimizes surprise across the cortical hierarchy.','Cortex-wide');


-- ============================================================
-- STEP 3: ARTIFICIAL_STRUCTURE (15 rows)
-- ============================================================
INSERT INTO artificial_structure (art_name, art_type, description, architecture_family) VALUES ('Convolutional Neural Network (CNN)','Architecture Component','A feedforward network applying learned filter kernels hierarchically across spatial inputs. Lower layers detect edges; deeper layers encode complex object parts and categories.','CNN');
INSERT INTO artificial_structure (art_name, art_type, description, architecture_family) VALUES ('Hierarchical Deep Network Layers','Layer Type','The stacked layer structure of deep networks where each successive layer computes increasingly abstract representations, mirroring the progressive abstraction of cortical hierarchies.','CNN / Deep Learning');
INSERT INTO artificial_structure (art_name, art_type, description, architecture_family) VALUES ('Sparse Autoencoder','Architecture Component','A neural network trained to reconstruct its input through a bottleneck with a sparsity constraint on activations. Encourages each unit to respond selectively to specific input features.','Autoencoder');
INSERT INTO artificial_structure (art_name, art_type, description, architecture_family) VALUES ('Dropout Regularization','Training Mechanism','A training technique that randomly sets neuron activations to zero during forward passes, producing sparse distributed representations and preventing co-adaptation of features.','General Deep Learning');
INSERT INTO artificial_structure (art_name, art_type, description, architecture_family) VALUES ('Long Short-Term Memory (LSTM)','Memory Module','A recurrent network architecture with gating mechanisms that selectively retain or discard information over long sequences, enabling long-range temporal dependencies.','RNN');
INSERT INTO artificial_structure (art_name, art_type, description, architecture_family) VALUES ('Continual Learning with Replay','Algorithm','A family of algorithms that store or regenerate examples of past tasks and interleave them with new training to prevent catastrophic forgetting. Computationally mirrors sleep memory replay.','Continual Learning');
INSERT INTO artificial_structure (art_name, art_type, description, architecture_family) VALUES ('Attention Head (Transformer)','Attention Mechanism','A component in transformer architectures that computes weighted sums over input positions using query-key-value dot products, allowing the model to focus on relevant context positions.','Transformer');
INSERT INTO artificial_structure (art_name, art_type, description, architecture_family) VALUES ('Multi-Head Self-Attention','Attention Mechanism','Multiple attention heads operating in parallel, each attending to different aspects of the input. The parallel structure mirrors the multiple functional channels in cortico-thalamic circuits.','Transformer');
INSERT INTO artificial_structure (art_name, art_type, description, architecture_family) VALUES ('Backpropagation','Training Mechanism','The algorithm used to compute gradients of the loss function with respect to all network weights by propagating error signals backward through the network.','General Deep Learning');
INSERT INTO artificial_structure (art_name, art_type, description, architecture_family) VALUES ('Plastic Synaptic Weights','Training Mechanism','Network weights that change through Hebbian-like fast-learning rules during inference, allowing within-episode adaptation without full retraining. Inspired by biological synaptic plasticity.','Meta-Learning');
INSERT INTO artificial_structure (art_name, art_type, description, architecture_family) VALUES ('Temporal Difference (TD) Learning','Algorithm','A reinforcement learning algorithm that updates value estimates based on the difference between successive predictions. The mathematical formalization of reward prediction error signaling.','Reinforcement Learning');
INSERT INTO artificial_structure (art_name, art_type, description, architecture_family) VALUES ('Variational Autoencoder (VAE)','Architecture Component','A generative model that encodes inputs into a probabilistic latent space and decodes samples from it. Implements approximate Bayesian inference, formally parallel to predictive coding.','Generative Model');
INSERT INTO artificial_structure (art_name, art_type, description, architecture_family) VALUES ('Predictive Coding Network','Architecture Component','A hierarchical network where each layer generates predictions for the layer below and only prediction errors propagate upward. A direct computational implementation of the predictive coding theory.','Predictive Coding');
INSERT INTO artificial_structure (art_name, art_type, description, architecture_family) VALUES ('Sequence-to-Sequence RNN','Architecture Component','A recurrent network that encodes an input sequence into a fixed-dimensional state and decodes it into an output sequence. Used in language, speech, and motor sequence generation tasks.','RNN');
INSERT INTO artificial_structure (art_name, art_type, description, architecture_family) VALUES ('Recurrent Neural Network (RNN)','Architecture Component','A class of networks with recurrent connections that maintain an internal state across time steps, enabling the modeling of temporal dynamics and sequential structure.','RNN');


-- ============================================================
-- STEP 4: BIO_STRUCTURE_CATEGORY (22 rows)
-- ============================================================
INSERT INTO bio_structure_category (bio_id, category_id) SELECT b.bio_id, c.category_id FROM biological_structure b, functional_category c WHERE b.bio_name = 'Primary Visual Cortex (V1)' AND c.category_name = 'Perception & Encoding';
INSERT INTO bio_structure_category (bio_id, category_id) SELECT b.bio_id, c.category_id FROM biological_structure b, functional_category c WHERE b.bio_name = 'Inferior Temporal Cortex (IT)' AND c.category_name = 'Perception & Encoding';
INSERT INTO bio_structure_category (bio_id, category_id) SELECT b.bio_id, c.category_id FROM biological_structure b, functional_category c WHERE b.bio_name = 'Ventral Visual Stream' AND c.category_name = 'Perception & Encoding';
INSERT INTO bio_structure_category (bio_id, category_id) SELECT b.bio_id, c.category_id FROM biological_structure b, functional_category c WHERE b.bio_name = 'Sparse Coding in V1' AND c.category_name = 'Perception & Encoding';
INSERT INTO bio_structure_category (bio_id, category_id) SELECT b.bio_id, c.category_id FROM biological_structure b, functional_category c WHERE b.bio_name = 'Hippocampus' AND c.category_name = 'Memory & Storage';
INSERT INTO bio_structure_category (bio_id, category_id) SELECT b.bio_id, c.category_id FROM biological_structure b, functional_category c WHERE b.bio_name = 'Hippocampus' AND c.category_name = 'Learning & Adaptation';
INSERT INTO bio_structure_category (bio_id, category_id) SELECT b.bio_id, c.category_id FROM biological_structure b, functional_category c WHERE b.bio_name = 'Sleep Replay (REM/NREM)' AND c.category_name = 'Memory & Storage';
INSERT INTO bio_structure_category (bio_id, category_id) SELECT b.bio_id, c.category_id FROM biological_structure b, functional_category c WHERE b.bio_name = 'Neocortex' AND c.category_name = 'Memory & Storage';
INSERT INTO bio_structure_category (bio_id, category_id) SELECT b.bio_id, c.category_id FROM biological_structure b, functional_category c WHERE b.bio_name = 'Neocortex' AND c.category_name = 'Learning & Adaptation';
INSERT INTO bio_structure_category (bio_id, category_id) SELECT b.bio_id, c.category_id FROM biological_structure b, functional_category c WHERE b.bio_name = 'Synaptic Plasticity (STDP)' AND c.category_name = 'Learning & Adaptation';
INSERT INTO bio_structure_category (bio_id, category_id) SELECT b.bio_id, c.category_id FROM biological_structure b, functional_category c WHERE b.bio_name = 'Hebbian Learning' AND c.category_name = 'Learning & Adaptation';
INSERT INTO bio_structure_category (bio_id, category_id) SELECT b.bio_id, c.category_id FROM biological_structure b, functional_category c WHERE b.bio_name = 'Prefrontal Cortex (PFC)' AND c.category_name = 'Attention & Selectivity';
INSERT INTO bio_structure_category (bio_id, category_id) SELECT b.bio_id, c.category_id FROM biological_structure b, functional_category c WHERE b.bio_name = 'Prefrontal Cortex (PFC)' AND c.category_name = 'Decision & Prediction';
INSERT INTO bio_structure_category (bio_id, category_id) SELECT b.bio_id, c.category_id FROM biological_structure b, functional_category c WHERE b.bio_name = 'Prefrontal Cortex (PFC)' AND c.category_name = 'Memory & Storage';
INSERT INTO bio_structure_category (bio_id, category_id) SELECT b.bio_id, c.category_id FROM biological_structure b, functional_category c WHERE b.bio_name = 'Cortico-Thalamic Circuit' AND c.category_name = 'Attention & Selectivity';
INSERT INTO bio_structure_category (bio_id, category_id) SELECT b.bio_id, c.category_id FROM biological_structure b, functional_category c WHERE b.bio_name = 'Parietal Cortex' AND c.category_name = 'Attention & Selectivity';
INSERT INTO bio_structure_category (bio_id, category_id) SELECT b.bio_id, c.category_id FROM biological_structure b, functional_category c WHERE b.bio_name = 'Dopaminergic System' AND c.category_name = 'Decision & Prediction';
INSERT INTO bio_structure_category (bio_id, category_id) SELECT b.bio_id, c.category_id FROM biological_structure b, functional_category c WHERE b.bio_name = 'Dopaminergic System' AND c.category_name = 'Learning & Adaptation';
INSERT INTO bio_structure_category (bio_id, category_id) SELECT b.bio_id, c.category_id FROM biological_structure b, functional_category c WHERE b.bio_name = 'Basal Ganglia' AND c.category_name = 'Decision & Prediction';
INSERT INTO bio_structure_category (bio_id, category_id) SELECT b.bio_id, c.category_id FROM biological_structure b, functional_category c WHERE b.bio_name = 'Primary Motor Cortex (M1)' AND c.category_name = 'Output & Generation';
INSERT INTO bio_structure_category (bio_id, category_id) SELECT b.bio_id, c.category_id FROM biological_structure b, functional_category c WHERE b.bio_name = 'Predictive Coding Hierarchy' AND c.category_name = 'Decision & Prediction';
INSERT INTO bio_structure_category (bio_id, category_id) SELECT b.bio_id, c.category_id FROM biological_structure b, functional_category c WHERE b.bio_name = 'Predictive Coding Hierarchy' AND c.category_name = 'Perception & Encoding';


-- ============================================================
-- STEP 5: ART_STRUCTURE_CATEGORY (20 rows)
-- ============================================================
INSERT INTO art_structure_category (art_id, category_id) SELECT a.art_id, c.category_id FROM artificial_structure a, functional_category c WHERE a.art_name = 'Convolutional Neural Network (CNN)' AND c.category_name = 'Perception & Encoding';
INSERT INTO art_structure_category (art_id, category_id) SELECT a.art_id, c.category_id FROM artificial_structure a, functional_category c WHERE a.art_name = 'Hierarchical Deep Network Layers' AND c.category_name = 'Perception & Encoding';
INSERT INTO art_structure_category (art_id, category_id) SELECT a.art_id, c.category_id FROM artificial_structure a, functional_category c WHERE a.art_name = 'Hierarchical Deep Network Layers' AND c.category_name = 'Memory & Storage';
INSERT INTO art_structure_category (art_id, category_id) SELECT a.art_id, c.category_id FROM artificial_structure a, functional_category c WHERE a.art_name = 'Sparse Autoencoder' AND c.category_name = 'Perception & Encoding';
INSERT INTO art_structure_category (art_id, category_id) SELECT a.art_id, c.category_id FROM artificial_structure a, functional_category c WHERE a.art_name = 'Dropout Regularization' AND c.category_name = 'Perception & Encoding';
INSERT INTO art_structure_category (art_id, category_id) SELECT a.art_id, c.category_id FROM artificial_structure a, functional_category c WHERE a.art_name = 'Dropout Regularization' AND c.category_name = 'Learning & Adaptation';
INSERT INTO art_structure_category (art_id, category_id) SELECT a.art_id, c.category_id FROM artificial_structure a, functional_category c WHERE a.art_name = 'Long Short-Term Memory (LSTM)' AND c.category_name = 'Memory & Storage';
INSERT INTO art_structure_category (art_id, category_id) SELECT a.art_id, c.category_id FROM artificial_structure a, functional_category c WHERE a.art_name = 'Continual Learning with Replay' AND c.category_name = 'Memory & Storage';
INSERT INTO art_structure_category (art_id, category_id) SELECT a.art_id, c.category_id FROM artificial_structure a, functional_category c WHERE a.art_name = 'Attention Head (Transformer)' AND c.category_name = 'Attention & Selectivity';
INSERT INTO art_structure_category (art_id, category_id) SELECT a.art_id, c.category_id FROM artificial_structure a, functional_category c WHERE a.art_name = 'Multi-Head Self-Attention' AND c.category_name = 'Attention & Selectivity';
INSERT INTO art_structure_category (art_id, category_id) SELECT a.art_id, c.category_id FROM artificial_structure a, functional_category c WHERE a.art_name = 'Multi-Head Self-Attention' AND c.category_name = 'Memory & Storage';
INSERT INTO art_structure_category (art_id, category_id) SELECT a.art_id, c.category_id FROM artificial_structure a, functional_category c WHERE a.art_name = 'Backpropagation' AND c.category_name = 'Learning & Adaptation';
INSERT INTO art_structure_category (art_id, category_id) SELECT a.art_id, c.category_id FROM artificial_structure a, functional_category c WHERE a.art_name = 'Plastic Synaptic Weights' AND c.category_name = 'Learning & Adaptation';
INSERT INTO art_structure_category (art_id, category_id) SELECT a.art_id, c.category_id FROM artificial_structure a, functional_category c WHERE a.art_name = 'Temporal Difference (TD) Learning' AND c.category_name = 'Decision & Prediction';
INSERT INTO art_structure_category (art_id, category_id) SELECT a.art_id, c.category_id FROM artificial_structure a, functional_category c WHERE a.art_name = 'Temporal Difference (TD) Learning' AND c.category_name = 'Learning & Adaptation';
INSERT INTO art_structure_category (art_id, category_id) SELECT a.art_id, c.category_id FROM artificial_structure a, functional_category c WHERE a.art_name = 'Variational Autoencoder (VAE)' AND c.category_name = 'Decision & Prediction';
INSERT INTO art_structure_category (art_id, category_id) SELECT a.art_id, c.category_id FROM artificial_structure a, functional_category c WHERE a.art_name = 'Predictive Coding Network' AND c.category_name = 'Decision & Prediction';
INSERT INTO art_structure_category (art_id, category_id) SELECT a.art_id, c.category_id FROM artificial_structure a, functional_category c WHERE a.art_name = 'Sequence-to-Sequence RNN' AND c.category_name = 'Output & Generation';
INSERT INTO art_structure_category (art_id, category_id) SELECT a.art_id, c.category_id FROM artificial_structure a, functional_category c WHERE a.art_name = 'Recurrent Neural Network (RNN)' AND c.category_name = 'Output & Generation';
INSERT INTO art_structure_category (art_id, category_id) SELECT a.art_id, c.category_id FROM artificial_structure a, functional_category c WHERE a.art_name = 'Recurrent Neural Network (RNN)' AND c.category_name = 'Memory & Storage';


-- ============================================================
-- STEP 6: PARALLEL (20 rows)
-- ============================================================
INSERT INTO parallel (bio_id, art_id, category_id, parallel_name, parallel_type, design_insight, confidence_level) SELECT b.bio_id, a.art_id, c.category_id, 'V1 Simple Cells and Convolutional Filters', 'Structural', 'V1 simple cells detect oriented edges through localized linear filters arranged hierarchically. CNNs independently converged on the same solution. This structural identity confirms that edge detection via learned spatial filters is an optimal strategy for visual encoding. Deeper cortical areas (V2, V4, IT) could template the design of the remaining CNN layers more precisely.', 'High' FROM biological_structure b, artificial_structure a, functional_category c WHERE b.bio_name = 'Primary Visual Cortex (V1)' AND a.art_name = 'Convolutional Neural Network (CNN)' AND c.category_name = 'Perception & Encoding';
INSERT INTO parallel (bio_id, art_id, category_id, parallel_name, parallel_type, design_insight, confidence_level) SELECT b.bio_id, a.art_id, c.category_id, 'Sparse Coding in V1 and Sparse Autoencoders', 'Computational', 'V1 maintains a sparse code: at any moment only 1-5% of neurons are active, maximizing information capacity. Sparse autoencoders replicate this constraint artificially. The biological solution suggests sparsity should be a fundamental design principle rather than optional regularization.', 'High' FROM biological_structure b, artificial_structure a, functional_category c WHERE b.bio_name = 'Sparse Coding in V1' AND a.art_name = 'Sparse Autoencoder' AND c.category_name = 'Perception & Encoding';
INSERT INTO parallel (bio_id, art_id, category_id, parallel_name, parallel_type, design_insight, confidence_level) SELECT b.bio_id, a.art_id, c.category_id, 'Ventral Stream Hierarchy and Deep Network Layer Stack', 'Structural', 'The ventral stream processes information through progressively abstract levels: edges in V1, textures in V2, shapes in V4, objects in IT. Deep networks mirror this exactly. AI should investigate whether replicating the biological inter-area connectivity patterns yields representational advantages over current architectures.', 'High' FROM biological_structure b, artificial_structure a, functional_category c WHERE b.bio_name = 'Ventral Visual Stream' AND a.art_name = 'Hierarchical Deep Network Layers' AND c.category_name = 'Perception & Encoding';
INSERT INTO parallel (bio_id, art_id, category_id, parallel_name, parallel_type, design_insight, confidence_level) SELECT b.bio_id, a.art_id, c.category_id, 'V1 Lateral Inhibition and Dropout Regularization', 'Computational', 'Lateral inhibition in V1 enforces sparse coding by suppressing co-active neurons. Dropout achieves a statistically similar effect by randomly zeroing activations. However biological sparsity is structured and stimulus-specific, not random. Structured stimulus-conditioned dropout could outperform random dropout as a regularization strategy.', 'Medium' FROM biological_structure b, artificial_structure a, functional_category c WHERE b.bio_name = 'Sparse Coding in V1' AND a.art_name = 'Dropout Regularization' AND c.category_name = 'Perception & Encoding';
INSERT INTO parallel (bio_id, art_id, category_id, parallel_name, parallel_type, design_insight, confidence_level) SELECT b.bio_id, a.art_id, c.category_id, 'Hippocampal Gating and LSTM Gates', 'Functional', 'The hippocampus gates what enters long-term memory using pattern separation and pattern completion circuits. The LSTM replicates this functional role via input and forget gates. A complementary learning systems architecture with separate fast and slow memory networks operating simultaneously would better reflect the biology.', 'Medium' FROM biological_structure b, artificial_structure a, functional_category c WHERE b.bio_name = 'Hippocampus' AND a.art_name = 'Long Short-Term Memory (LSTM)' AND c.category_name = 'Memory & Storage';
INSERT INTO parallel (bio_id, art_id, category_id, parallel_name, parallel_type, design_insight, confidence_level) SELECT b.bio_id, a.art_id, c.category_id, 'Biological Sleep Replay and Artificial Memory Replay', 'Functional', 'During sleep the hippocampus replays compressed memory traces to the neocortex enabling knowledge consolidation without overwriting old memories. Continual learning with replay implements the same principle. Key insight: biological replay is generative, compressed, and hierarchically organized. AI systems should use generative replay rather than stored exemplars.', 'High' FROM biological_structure b, artificial_structure a, functional_category c WHERE b.bio_name = 'Sleep Replay (REM/NREM)' AND a.art_name = 'Continual Learning with Replay' AND c.category_name = 'Memory & Storage';
INSERT INTO parallel (bio_id, art_id, category_id, parallel_name, parallel_type, design_insight, confidence_level) SELECT b.bio_id, a.art_id, c.category_id, 'Hippocampal Indexing Theory and Replay-Based Continual Learning', 'Functional', 'The hippocampal indexing theory proposes that the hippocampus stores pointers to distributed neocortical representations. Replay-based continual learning uses stored or generated memories to prevent catastrophic forgetting. The biological system stores compressed indices, not raw data. AI architectures should implement compressed latent-space replay to match biological efficiency.', 'High' FROM biological_structure b, artificial_structure a, functional_category c WHERE b.bio_name = 'Hippocampus' AND a.art_name = 'Continual Learning with Replay' AND c.category_name = 'Memory & Storage';
INSERT INTO parallel (bio_id, art_id, category_id, parallel_name, parallel_type, design_insight, confidence_level) SELECT b.bio_id, a.art_id, c.category_id, 'Spike-Timing-Dependent Plasticity and Backpropagation', 'Computational', 'STDP adjusts synaptic weights based on the relative timing of pre- and post-synaptic spikes in a local biologically plausible manner. Backpropagation requires a global error signal (the weight transport problem). Both achieve similar learning outcomes. Designing local learning rules that approximate backpropagation gradients without global error propagation is the critical open problem this parallel identifies.', 'High' FROM biological_structure b, artificial_structure a, functional_category c WHERE b.bio_name = 'Synaptic Plasticity (STDP)' AND a.art_name = 'Backpropagation' AND c.category_name = 'Learning & Adaptation';
INSERT INTO parallel (bio_id, art_id, category_id, parallel_name, parallel_type, design_insight, confidence_level) SELECT b.bio_id, a.art_id, c.category_id, 'Hebbian Plasticity and Differentiable Plastic Weights', 'Computational', 'Hebbian learning is the biological rule for rapid experience-dependent synaptic change. Differentiable plasticity implements Hebbian-like fast weights that change during a forward pass without gradient descent, enabling within-episode adaptation. This points toward a two-timescale architecture: slow meta-learning via gradient descent and fast Hebbian adaptation during inference.', 'High' FROM biological_structure b, artificial_structure a, functional_category c WHERE b.bio_name = 'Hebbian Learning' AND a.art_name = 'Plastic Synaptic Weights' AND c.category_name = 'Learning & Adaptation';
INSERT INTO parallel (bio_id, art_id, category_id, parallel_name, parallel_type, design_insight, confidence_level) SELECT b.bio_id, a.art_id, c.category_id, 'Dopamine Prediction Error and Temporal Difference Learning', 'Computational', 'This is the most precisely established parallel in neuro-AI. Dopamine neurons fire exactly as the TD error signal predicts: phasic activation for unexpected reward, silence for predicted reward, pause for omitted reward. The mathematical identity is virtually certain. The design insight: the biological system is remarkably energy-efficient. AI could adopt biologically realistic sparse event-driven TD updates instead of dense synchronous updates.', 'High' FROM biological_structure b, artificial_structure a, functional_category c WHERE b.bio_name = 'Dopaminergic System' AND a.art_name = 'Temporal Difference (TD) Learning' AND c.category_name = 'Decision & Prediction';
INSERT INTO parallel (bio_id, art_id, category_id, parallel_name, parallel_type, design_insight, confidence_level) SELECT b.bio_id, a.art_id, c.category_id, 'Basal Ganglia Reward Circuit and TD Reinforcement Learning', 'Structural', 'The basal ganglia implements action selection through anatomically distinct direct and indirect pathways that parallel the go/no-go logic of RL action selection. AI RL architectures could adopt the biologically separate direct and indirect pathway design to create more efficient action gating, particularly for sparse reward environments.', 'High' FROM biological_structure b, artificial_structure a, functional_category c WHERE b.bio_name = 'Basal Ganglia' AND a.art_name = 'Temporal Difference (TD) Learning' AND c.category_name = 'Decision & Prediction';
INSERT INTO parallel (bio_id, art_id, category_id, parallel_name, parallel_type, design_insight, confidence_level) SELECT b.bio_id, a.art_id, c.category_id, 'Predictive Coding Cortical Hierarchy and Variational Autoencoders', 'Computational', 'Predictive coding proposes the cortex maintains generative models of sensory input, sending predictions downward and only propagating prediction errors upward. Variational autoencoders implement formally identical Bayesian inference. Implementing VAE inference as a local continuous-time predictive coding process could yield a more biologically plausible and energy-efficient generative model.', 'Medium' FROM biological_structure b, artificial_structure a, functional_category c WHERE b.bio_name = 'Predictive Coding Hierarchy' AND a.art_name = 'Variational Autoencoder (VAE)' AND c.category_name = 'Decision & Prediction';
INSERT INTO parallel (bio_id, art_id, category_id, parallel_name, parallel_type, design_insight, confidence_level) SELECT b.bio_id, a.art_id, c.category_id, 'Cortical Predictive Coding and Predictive Coding Networks', 'Structural', 'Predictive Coding Networks directly implement the neuroscientific theory of cortical computation. Each layer maintains both a representation and a prediction of the layer below, with only error units propagating upward. The design advantage: such networks can learn in an unsupervised and online manner without backpropagation because the local prediction error is the training signal at every layer simultaneously.', 'High' FROM biological_structure b, artificial_structure a, functional_category c WHERE b.bio_name = 'Predictive Coding Hierarchy' AND a.art_name = 'Predictive Coding Network' AND c.category_name = 'Decision & Prediction';
INSERT INTO parallel (bio_id, art_id, category_id, parallel_name, parallel_type, design_insight, confidence_level) SELECT b.bio_id, a.art_id, c.category_id, 'Cortico-Thalamic Attention Gating and Multi-Head Self-Attention', 'Structural', 'The cortico-thalamic loop implements attention by selectively amplifying or suppressing thalamic relay of sensory signals through multiple parallel channels. Multi-head self-attention implements a structurally analogous parallel gating mechanism. Thalamic gating is modulated by neuromodulators to switch between exploration and exploitation modes. AI attention heads have no equivalent modulation mechanism.', 'Medium' FROM biological_structure b, artificial_structure a, functional_category c WHERE b.bio_name = 'Cortico-Thalamic Circuit' AND a.art_name = 'Multi-Head Self-Attention' AND c.category_name = 'Attention & Selectivity';
INSERT INTO parallel (bio_id, art_id, category_id, parallel_name, parallel_type, design_insight, confidence_level) SELECT b.bio_id, a.art_id, c.category_id, 'Prefrontal Top-Down Attention and Transformer Attention Heads', 'Functional', 'The PFC implements top-down attentional control by biasing activity in sensory cortices toward task-relevant features. Transformer attention heads implement a learned weighting over input positions that serves a functionally equivalent role. The biological system uses anatomically distinct bottom-up and top-down attention pathways. Designing separate bottom-up and top-down attention modules reflecting the PFC-parietal distinction could improve task-directed attention in AI.', 'High' FROM biological_structure b, artificial_structure a, functional_category c WHERE b.bio_name = 'Prefrontal Cortex (PFC)' AND a.art_name = 'Attention Head (Transformer)' AND c.category_name = 'Attention & Selectivity';
INSERT INTO parallel (bio_id, art_id, category_id, parallel_name, parallel_type, design_insight, confidence_level) SELECT b.bio_id, a.art_id, c.category_id, 'Parietal Spatial Attention and Positional Attention in Transformers', 'Functional', 'The parietal cortex implements a dynamic spatial saliency map directing processing resources to behaviorally relevant locations. Transformer attention heads compute position-weighted representations with positional encodings. Implementing a biologically realistic dynamic saliency map rather than static positional encodings could improve spatial reasoning in vision transformers.', 'Medium' FROM biological_structure b, artificial_structure a, functional_category c WHERE b.bio_name = 'Parietal Cortex' AND a.art_name = 'Attention Head (Transformer)' AND c.category_name = 'Attention & Selectivity';
INSERT INTO parallel (bio_id, art_id, category_id, parallel_name, parallel_type, design_insight, confidence_level) SELECT b.bio_id, a.art_id, c.category_id, 'Neocortical Columnar Organization and Deep Layer Hierarchy', 'Structural', 'The neocortex organizes knowledge in cortical columns spanning all 6 layers with lateral connections between columns encoding relationships. Deep networks use horizontal layer stacking without the vertical columnar organization. Implementing a columnar architecture with feature-specific columns and lateral inter-column connections could provide more structured and interpretable representations.', 'Medium' FROM biological_structure b, artificial_structure a, functional_category c WHERE b.bio_name = 'Neocortex' AND a.art_name = 'Hierarchical Deep Network Layers' AND c.category_name = 'Memory & Storage';
INSERT INTO parallel (bio_id, art_id, category_id, parallel_name, parallel_type, design_insight, confidence_level) SELECT b.bio_id, a.art_id, c.category_id, 'Motor Cortex Population Dynamics and Sequence-to-Sequence RNNs', 'Functional', 'Motor cortex generates sequential motor commands as trajectories through a high-dimensional population state space. The population activity rotates through a manifold during movement. Seq2Seq RNNs encode-then-decode sequential outputs through a similarly high-dimensional hidden state. Explicitly constraining RNN hidden state trajectories to lie on low-dimensional rotational manifolds could produce smoother more energy-efficient sequence generation.', 'Medium' FROM biological_structure b, artificial_structure a, functional_category c WHERE b.bio_name = 'Primary Motor Cortex (M1)' AND a.art_name = 'Sequence-to-Sequence RNN' AND c.category_name = 'Output & Generation';
INSERT INTO parallel (bio_id, art_id, category_id, parallel_name, parallel_type, design_insight, confidence_level) SELECT b.bio_id, a.art_id, c.category_id, 'Motor Cortex Recurrent Dynamics and Recurrent Neural Networks', 'Structural', 'Primary motor cortex contains dense recurrent excitatory connections between pyramidal neurons that sustain activity across time. RNNs implement recurrence through explicit feedback connections. The biological network uses excitatory and inhibitory neurons in approximately 80:20 ratio with structured connectivity. Structuring RNN connectivity to reflect the biological E/I balance could improve temporal stability and reduce vanishing gradient problems.', 'Medium' FROM biological_structure b, artificial_structure a, functional_category c WHERE b.bio_name = 'Primary Motor Cortex (M1)' AND a.art_name = 'Recurrent Neural Network (RNN)' AND c.category_name = 'Output & Generation';
INSERT INTO parallel (bio_id, art_id, category_id, parallel_name, parallel_type, design_insight, confidence_level) SELECT b.bio_id, a.art_id, c.category_id, 'Prefrontal Working Memory and Multi-Head Attention Context Window', 'Structural', 'The prefrontal cortex maintains a limited-capacity working memory buffer held in active neural representations through sustained firing. The transformer context window is the functional equivalent. Biological working memory is an active dynamically updated representation regulated by dopamine and norepinephrine. Implementing neuromodulatory gating of the attention context where certain tokens are actively maintained or suppressed based on task relevance mirrors the biological reality of PFC working memory.', 'High' FROM biological_structure b, artificial_structure a, functional_category c WHERE b.bio_name = 'Prefrontal Cortex (PFC)' AND a.art_name = 'Multi-Head Self-Attention' AND c.category_name = 'Attention & Selectivity';


-- ============================================================
-- STEP 7: INSTITUTION (15 rows)
-- ============================================================
INSERT INTO institution (institution_name, institution_type, country, city) VALUES ('Massachusetts Institute of Technology','Academic','USA','Cambridge');
INSERT INTO institution (institution_name, institution_type, country, city) VALUES ('Stanford University','Academic','USA','Stanford');
INSERT INTO institution (institution_name, institution_type, country, city) VALUES ('UC Berkeley','Academic','USA','Berkeley');
INSERT INTO institution (institution_name, institution_type, country, city) VALUES ('Cornell University','Academic','USA','Ithaca');
INSERT INTO institution (institution_name, institution_type, country, city) VALUES ('University of Cambridge','Academic','UK','Cambridge');
INSERT INTO institution (institution_name, institution_type, country, city) VALUES ('University College London','Academic','UK','London');
INSERT INTO institution (institution_name, institution_type, country, city) VALUES ('McGill University','Academic','Canada','Montreal');
INSERT INTO institution (institution_name, institution_type, country, city) VALUES ('DeepMind','Industry','UK','London');
INSERT INTO institution (institution_name, institution_type, country, city) VALUES ('Cold Spring Harbor Laboratory','Non-profit','USA','Cold Spring Harbor');
INSERT INTO institution (institution_name, institution_type, country, city) VALUES ('Columbia University','Academic','USA','New York');
INSERT INTO institution (institution_name, institution_type, country, city) VALUES ('UC San Diego','Academic','USA','La Jolla');
INSERT INTO institution (institution_name, institution_type, country, city) VALUES ('Uber AI Labs','Industry','USA','San Francisco');
INSERT INTO institution (institution_name, institution_type, country, city) VALUES ('Harvard University','Academic','USA','Cambridge');
INSERT INTO institution (institution_name, institution_type, country, city) VALUES ('University of Amsterdam','Academic','Netherlands','Amsterdam');
INSERT INTO institution (institution_name, institution_type, country, city) VALUES ('Mila - Quebec AI Institute','Non-profit','Canada','Montreal');


-- ============================================================
-- STEP 8: FUNDING_SOURCE (8 rows)
-- ============================================================
INSERT INTO funding_source (funder_name, funder_type, country, potential_bias) VALUES ('National Institutes of Health','Government','USA','Minimal commercial bias. May prioritize translational medical applications over foundational AI research.');
INSERT INTO funding_source (funder_name, funder_type, country, potential_bias) VALUES ('National Science Foundation','Government','USA','Minimal bias. Broad mandate covering both foundational and applied research.');
INSERT INTO funding_source (funder_name, funder_type, country, potential_bias) VALUES ('DARPA','Government','USA','Moderate bias toward defense applications and rapid practical deployment.');
INSERT INTO funding_source (funder_name, funder_type, country, potential_bias) VALUES ('European Research Council','Government','EU','Minimal bias. Strong emphasis on fundamental research and open access publication.');
INSERT INTO funding_source (funder_name, funder_type, country, potential_bias) VALUES ('Google DeepMind','Industry','UK','High commercial bias. Research may favor architectures scalable under large compute budgets and results favorable to large language model development.');
INSERT INTO funding_source (funder_name, funder_type, country, potential_bias) VALUES ('Simons Foundation','Non-profit','USA','Low bias. Focuses on fundamental science with strong track record of supporting high-risk basic research in neuroscience and mathematics.');
INSERT INTO funding_source (funder_name, funder_type, country, potential_bias) VALUES ('Canadian Institute for Advanced Research','Non-profit','Canada','Low-to-moderate bias. CIFAR AI chairs program creates ties to industry partners that may influence research directions.');
INSERT INTO funding_source (funder_name, funder_type, country, potential_bias) VALUES ('Wellcome Trust','Non-profit','UK','Low bias. Primarily funds biomedical and neuroscience research with strong open access mandate.');


-- ============================================================
-- STEP 9: AUTHOR (20 rows)
-- ============================================================
INSERT INTO author (first_name, last_name, primary_domain, h_index) VALUES ('Daniel','Yamins','Both',32);
INSERT INTO author (first_name, last_name, primary_domain, h_index) VALUES ('James','DiCarlo','Both',65);
INSERT INTO author (first_name, last_name, primary_domain, h_index) VALUES ('Bruno','Olshausen','Both',50);
INSERT INTO author (first_name, last_name, primary_domain, h_index) VALUES ('David','Field','Neuroscience',38);
INSERT INTO author (first_name, last_name, primary_domain, h_index) VALUES ('Wolfram','Schultz','Neuroscience',82);
INSERT INTO author (first_name, last_name, primary_domain, h_index) VALUES ('Peter','Dayan','Both',80);
INSERT INTO author (first_name, last_name, primary_domain, h_index) VALUES ('Blake','Richards','Both',28);
INSERT INTO author (first_name, last_name, primary_domain, h_index) VALUES ('Timothy','Lillicrap','Both',40);
INSERT INTO author (first_name, last_name, primary_domain, h_index) VALUES ('Yoshua','Bengio','AI',150);
INSERT INTO author (first_name, last_name, primary_domain, h_index) VALUES ('Anthony','Zador','Both',45);
INSERT INTO author (first_name, last_name, primary_domain, h_index) VALUES ('Nikolaus','Kriegeskorte','Both',42);
INSERT INTO author (first_name, last_name, primary_domain, h_index) VALUES ('Timothy','Tadros','Both',8);
INSERT INTO author (first_name, last_name, primary_domain, h_index) VALUES ('Maxim','Bazhenov','Both',38);
INSERT INTO author (first_name, last_name, primary_domain, h_index) VALUES ('Thomas','Miconi','AI',15);
INSERT INTO author (first_name, last_name, primary_domain, h_index) VALUES ('Cengiz','Pehlevan','Both',22);
INSERT INTO author (first_name, last_name, primary_domain, h_index) VALUES ('Demis','Hassabis','Both',55);
INSERT INTO author (first_name, last_name, primary_domain, h_index) VALUES ('Adam','Marblestone','Both',18);
INSERT INTO author (first_name, last_name, primary_domain, h_index) VALUES ('Konrad','Kording','Both',52);
INSERT INTO author (first_name, last_name, primary_domain, h_index) VALUES ('Oscar','Gonzalez','Both',10);
INSERT INTO author (first_name, last_name, primary_domain, h_index) VALUES ('Guillaume','Etter','Both',5);


-- ============================================================
-- STEP 10: PAPER (57 rows)
-- ============================================================

-- PERCEPTION & ENCODING (12 papers)
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Performance-optimized hierarchical models predict neural responses in higher visual cortex',2014,'Proceedings of the National Academy of Sciences','10.1073/pnas.1403112111','Computational','CNN','visual cortex, CNN, ventral stream, neural responses, hierarchical models','Demonstrates that task-optimized CNNs predict neural activity in primate visual cortical areas V4 and IT, establishing the quantitative equivalence between deep network representations and biological visual processing.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Deep Neural Networks Rival the Representation of Primate IT Cortex for Core Visual Object Recognition',2014,'PLOS Computational Biology','10.1371/journal.pcbi.1003963','Computational','CNN','IT cortex, deep neural networks, object recognition, representational similarity','Shows that state-of-the-art CNNs match the representational geometry of primate IT cortex for object recognition, making explicit the structural equivalence between deep network feature spaces and biological visual representations.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Deep Neural Networks Reveal a Gradient in the Complexity of Neural Representations across the Ventral Stream',2015,'Journal of Neuroscience','10.1523/JNEUROSCI.5023-14.2015','Computational','CNN','ventral stream, representational complexity, fMRI, deep learning','Uses fMRI to show that successive CNN layers predict activity in successive visual areas, mapping the computational hierarchy of the ventral stream onto deep network layer depth.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Comparison of deep neural networks to spatio-temporal cortical dynamics of human visual object recognition reveals hierarchical correspondence',2016,'Scientific Reports','10.1038/srep27755','Computational','CNN','cortical dynamics, MEG, object recognition, temporal hierarchy, CNN layers','Uses MEG to show that CNN layers correspond not just to spatial cortical areas but to specific temporal processing stages during visual object recognition in humans.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Using goal-driven deep learning models to understand sensory cortex',2016,'Nature Neuroscience','10.1038/nn.4244','Review','CNN','goal-driven models, sensory cortex, ventral stream, auditory cortex, review','Foundational review arguing that task-optimized deep networks trained on ethologically relevant tasks are the best current models of sensory cortical function.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Unsupervised neural network models of the ventral visual stream',2021,'Proceedings of the National Academy of Sciences','10.1073/pnas.2014196118','Computational','CNN','unsupervised learning, ventral stream, contrastive learning, self-supervised','Shows that self-supervised contrastive learning networks achieve neural prediction accuracy in visual cortical areas matching or exceeding supervised models.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Emergence of simple-cell receptive field properties by learning a sparse code for natural images',1996,'Nature','10.1038/381607a0','Theoretical','Sparse Autoencoder','sparse coding, V1, simple cells, receptive fields, natural images, ICA','Landmark paper showing that training a network to produce sparse representations of natural images spontaneously produces oriented localized bandpass filters identical to simple cell receptive fields in V1.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Sparse coding with an overcomplete basis set: A strategy employed by V1?',1997,'Vision Research','10.1016/S0042-6989(97)00169-7','Theoretical','Sparse Autoencoder','sparse coding, overcomplete basis, V1, efficient coding, feature selectivity','Extends the sparse coding framework to overcomplete representations, arguing that V1 uses more basis vectors than input dimensions to achieve maximally sparse and efficient coding of natural scenes.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('The structure dilemma in biological and artificial neural networks',2021,'Scientific Reports','10.1038/s41598-021-01471-6','Computational','CNN','connectome, network structure, biological plausibility, ANN, structural comparison','Directly compares the structural properties of biological neural networks to artificial neural networks, identifying systematic differences in connectivity patterns.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('A computational architecture incorporating shallow brain networks: integrating parallel cortical and subcortical processing',2026,'Current Research in Neurobiology','10.1016/j.crneur.2026.100155','Computational','CNN','subcortical pathways, cortico-subcortical, predictive coding, decision-making, shallow networks','Presents a computational model combining cortical hierarchical processing with subcortical parallel pathways, showing that neglected subcortical-cortical interactions are necessary for explaining human perceptual decision-making behavior.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('A task-optimized neural network replicates human auditory behavior, predicts brain responses, and reveals a cortical processing hierarchy',2018,'Neuron','10.1016/j.neuron.2018.03.044','Computational','CNN','auditory cortex, task-optimized, speech recognition, cochleagram, auditory hierarchy','Demonstrates that CNNs optimized for speech and music recognition develop representations that predict neural responses along the auditory cortical hierarchy.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Activations of deep convolutional neural networks are aligned with gamma band activity of human visual cortex',2018,'Communications Biology','10.1038/s42003-018-0110-y','Experimental','CNN','gamma oscillations, EEG, visual cortex, CNN activations, electrophysiology','Uses EEG to show that CNN layer activations correlate specifically with gamma-band neural oscillations in human visual cortex.');

-- ATTENTION & SELECTIVITY (8 papers)
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Attention weights accurately predict language representations in the brain',2022,'arXiv','10.48550/arXiv.2212.01750','Computational','Transformer','attention weights, BERT, fMRI, language, brain representations, transformers','Shows that attention weights of transformer language models predict fMRI activity in language cortex, providing direct evidence that the computational attention mechanism corresponds to selective neural processing.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Transformer brain encoders explain human high-level visual responses',2025,'arXiv','10.48550/arXiv.2501.10965','Computational','Transformer','vision transformers, visual cortex, brain encoding, high-level vision, ViT','Demonstrates that vision transformer models better explain high-level visual cortical responses than CNNs, suggesting that the attention-based architecture captures aspects of biological visual processing that convolutional architectures miss.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Multihead self-attention in cortico-thalamic circuits',2025,'arXiv','10.48550/arXiv.2504.06354','Theoretical','Transformer','cortico-thalamic, multi-head attention, transformer, cortical columns, thalamus','Proposes and formalizes the structural correspondence between multi-head self-attention in transformers and the parallel processing channels of cortico-thalamic circuits.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('From Cognition to Computation: A Comparative Review of Human Attention and Transformer Architectures',2024,'arXiv','10.48550/arXiv.2407.01548','Review','Transformer','human attention, transformer, cognitive science, top-down, bottom-up, review','Systematically compares the cognitive neuroscience of human attention with transformer attention heads, identifying where the architectures align and where key biological features are absent.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('TransformerFAM: Feedback attention is working memory',2024,'arXiv','10.48550/arXiv.2404.09173','Computational','Transformer','working memory, feedback attention, transformer, long-context, recurrent processing','Introduces a transformer variant with feedback attention loops that create sustained activations across unlimited contexts, explicitly drawing on the neuroscience of prefrontal working memory.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Predictive Coding or Just Feature Discovery? An Alternative Account of Why Language Models Fit Brain Data',2024,'Neurobiology of Language','10.1162/nol_a_00143','Theoretical','Transformer','predictive coding, language models, brain data, feature discovery, representational alignment','Challenges the interpretation that transformer language models fit brain data because they implement predictive coding, proposing instead that representational alignment is driven by shared feature discovery.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Predicting brain activity using Transformers',2023,'bioRxiv','10.1101/2023.08.02.551743','Computational','Transformer','brain activity prediction, transformer, fMRI, encoding model, neural prediction','Develops transformer-based brain encoding models that predict fMRI responses to naturalistic stimuli across multiple cortical areas.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Parallel processing of working memory and temporal information by distinct types of cortical projection neurons',2021,'Nature Communications','10.1038/s41467-021-24565-z','Experimental','RNN','working memory, prefrontal cortex, IT neurons, PT neurons, temporal information','Identifies two distinct prefrontal projection neuron types with different roles in working memory maintenance and temporal processing.');

-- MEMORY & STORAGE (8 papers)
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Can sleep protect memories from catastrophic forgetting?',2020,'eLife','10.7554/eLife.51005','Computational','Continual Learning','sleep, catastrophic forgetting, memory consolidation, thalamocortical, continual learning','Demonstrates in a thalamocortical spiking network model that simulated sleep replay reverses catastrophic forgetting of old memories after new learning.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Sleep prevents catastrophic forgetting in spiking neural networks by forming a joint synaptic weight representation',2022,'PLOS Computational Biology','10.1371/journal.pcbi.1010628','Computational','Continual Learning','spiking neural network, sleep, catastrophic forgetting, synaptic weight space, replay','Shows that sleep-like spontaneous replay in spiking networks prevents catastrophic forgetting by moving synaptic weight configurations toward manifolds that simultaneously support multiple learned tasks.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Sleep-like unsupervised replay reduces catastrophic forgetting in artificial neural networks',2022,'Nature Communications','10.1038/s41467-022-34938-7','Computational','Continual Learning','REM sleep, unsupervised replay, continual learning, catastrophic forgetting, ANN','Proposes and validates a Sleep Replay Consolidation algorithm inspired by REM sleep dynamics, demonstrating that implementing a biological sleep phase enables continual learning of multiple tasks without accessing original training data.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Hebbian plasticity in parallel synaptic pathways: A circuit mechanism for systems memory consolidation',2021,'PLOS Biology','10.1371/journal.pbio.3001208','Theoretical','Plastic Synaptic Weights','Hebbian plasticity, memory consolidation, parallel pathways, complementary learning systems','Proposes a circuit-level mechanism using parallel synaptic pathways with different Hebbian plasticity timescales to implement the complementary learning systems theory.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Memory consolidation from a reinforcement learning perspective',2024,'Frontiers in Neuroscience','10.3389/fnins.2024.1331958','Review','Temporal Difference Learning','memory consolidation, reinforcement learning, hippocampus, neocortex, Dyna algorithm','Reviews the computational parallels between hippocampal-neocortical memory consolidation and the Dyna reinforcement learning architecture.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Memory-Augmented Transformers: A Systematic Review from Neuroscience Principles to Technical Solutions',2025,'arXiv','10.48550/arXiv.2508.10824','Review','Transformer','memory-augmented transformers, neuroscience, working memory, hippocampus, long-term memory','Systematically reviews how neuroscience memory principles have been incorporated into transformer architectures.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('RippleNet: A Recurrent Neural Network for Sharp Wave Ripple Detection',2021,'Frontiers in Neuroscience','10.3389/fnins.2021.685490','Computational','RNN','sharp wave ripples, hippocampus, RNN, memory replay, detection','Uses a recurrent neural network to detect hippocampal sharp wave ripples, the electrophysiological signature of memory replay events.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Barcode activity in a recurrent network model of the hippocampus enables efficient memory binding',2025,'eLife','10.7554/eLife.104921','Computational','RNN','hippocampus, barcode activity, pattern separation, memory binding, recurrent network','Proposes barcode-like sparse activity patterns in hippocampal circuits as a mechanism for unique memory indexing.');

-- LEARNING & ADAPTATION (10 papers)
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Differentiable plasticity: training plastic neural networks with backpropagation',2018,'Proceedings of ICML','10.48550/arXiv.1804.02464','Computational','Plastic Synaptic Weights','differentiable plasticity, Hebbian learning, meta-learning, fast weights, backpropagation','Introduces differentiable plasticity: networks learn both fixed weights via gradient descent and plastic Hebbian connections that update during inference, directly bridging biological Hebbian learning and gradient-based AI training.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Self-backpropagation of synaptic modifications elevates the efficiency of spiking and artificial neural networks',2021,'Science Advances','10.1126/sciadv.abh0451','Theoretical','Backpropagation','self-backpropagation, synaptic plasticity, biologically plausible, STDP, local learning','Proposes a biologically plausible learning rule called self-backpropagation in which synaptic modifications propagate backward through dendritic compartments without a global error signal.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Somato-dendritic synaptic plasticity and error-backpropagation in active dendrites',2016,'PLOS Computational Biology','10.1371/journal.pcbi.1004638','Theoretical','Backpropagation','dendritic computation, somatic-dendritic, backpropagation, calcium spikes, two-compartment model','Demonstrates that dendritic calcium spikes in a two-compartment neuron model implement a biologically plausible form of error backpropagation.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Neuroscience-inspired online unsupervised learning algorithms',2019,'arXiv','10.48550/arXiv.1908.01867','Theoretical','Backpropagation','similarity-based learning, unsupervised, biologically plausible, Hebbian, online learning','Develops a family of biologically plausible similarity-based unsupervised learning algorithms that can learn useful representations without backpropagation or labeled data.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Bridging Brains and Machines: A Unified Frontier in Neuroscience, Artificial Intelligence, and Neuromorphic Systems',2025,'arXiv','10.48550/arXiv.2503.01735','Review','Mixed','neuromorphic, neuro-AI, spiking networks, brain-machine interface, review','Comprehensive review mapping the current state of the neuro-AI intersection across computational neuroscience, AI architecture, and neuromorphic hardware.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('The brain as a blueprint: a survey of brain-inspired approaches to learning in artificial intelligence',2025,'arXiv','10.48550/arXiv.2511.04455','Review','Mixed','brain-inspired AI, synaptic plasticity, error propagation, continual learning, survey','Surveys successful implementations of brain-inspired learning principles in deep learning, identifying where biological discoveries could drive the next generation of AI learning algorithms.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Model-based inference of synaptic plasticity rules',2024,'bioRxiv','10.1101/2024.07.23.604840','Computational','Backpropagation','synaptic plasticity rules, model-based inference, STDP, learning rule identification','Develops a framework for inferring synaptic plasticity rules from observed neural data, enabling systematic comparison between biological plasticity and gradient-based learning rules.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('A deep learning framework for neuroscience',2019,'Nature Neuroscience','10.1038/s41593-019-0520-2','Review','Mixed','deep learning, neuroscience framework, credit assignment, optimization, biological plausibility','Proposes a unified framework for using deep learning concepts to understand brain computation, covering credit assignment, optimization objectives, and architectural constraints. Authored by Richards, Lillicrap, and Bengio.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Recent Advances at the Interface of Neuroscience and Artificial Neural Networks',2022,'Journal of Neuroscience','10.1523/JNEUROSCI.1503-22.2022','Review','Mixed','neuromodulation, recurrent networks, CNNs, neuro-AI interface, review','Reviews recent findings at the neuroscience-AI intersection with focus on neuromodulatory systems and their implications for designing context-sensitive AI architectures.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Emergence of sparse coding, balance and decorrelation from a biologically-grounded spiking neural network model of V1',2025,'PLOS Computational Biology','10.1371/journal.pcbi.1013644','Computational','Sparse Autoencoder','V1, spiking network, sparse coding, E/I balance, decorrelation, receptive fields','Shows that a biologically realistic spiking network model with excitatory-inhibitory balance spontaneously develops sparse coding and orientation-selective receptive fields matching experimental V1 data.');

-- DECISION & PREDICTION (10 papers)
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('A neural substrate of prediction and reward',1997,'Science','10.1126/science.275.5306.1593','Experimental','Temporal Difference Learning','dopamine, reward prediction error, temporal difference, conditioning, reinforcement learning','Foundational paper demonstrating that primate dopamine neurons signal reward prediction errors exactly as predicted by the temporal difference reinforcement learning algorithm.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Dopamine reward prediction error coding',2016,'Dialogues in Clinical Neuroscience','10.31887/DCNS.2016.18.1/wschultz','Review','Temporal Difference Learning','dopamine, reward prediction error, TD learning, economic utility, addiction','Comprehensive review of two decades of work establishing dopamine neurons as a biological implementation of temporal difference error coding.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Active Predictive Coding: A Unifying Neural Model for Active Perception, Compositional Learning, and Hierarchical Planning',2024,'Neural Computation','10.1162/neco_a_01672','Theoretical','Predictive Coding Network','active inference, predictive coding, hierarchical planning, compositional learning, active perception','Extends the predictive coding framework to active inference, showing how a hierarchical predictive coding network can unify perception, learning, and action planning.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Toward an integration of deep learning and neuroscience',2016,'Frontiers in Computational Neuroscience','10.3389/fncom.2016.00094','Theoretical','Mixed','deep learning, neuroscience, cost functions, credit assignment, modularity','Systematic analysis of how neuroscience-inspired cost functions, credit assignment methods, and modular architectural constraints could be incorporated into deep learning.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Neuroscience-inspired artificial intelligence',2017,'Neuron','10.1016/j.neuron.2017.06.011','Review','Mixed','neuroscience, AI, DeepMind, attention, memory, reinforcement learning, review','Influential DeepMind review of how neuroscience has historically contributed to AI breakthroughs and how the next generation could benefit from attention, episodic memory, and continual learning principles.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('A critique of pure learning and what artificial neural networks can learn from animal brains',2019,'Nature Communications','10.1038/s41467-019-11786-6','Theoretical','Mixed','inductive biases, genomic bottleneck, animal brains, learning efficiency, innate structure','Argues that AI relies too heavily on learning from experience and neglects innate structure encoded in the genome, proposing that AI should incorporate biologically-inspired inductive biases.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Building machines that learn and think like people',2017,'Behavioral and Brain Sciences','10.1017/S0140525X16001837','Theoretical','Mixed','human cognition, causal models, compositional representations, learning to learn, Bayesian','Argues that AI systems should incorporate intuitive physics, intuitive psychology, causal models, and compositional representations, drawing on cognitive science as a blueprint.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Catalyzing next-generation artificial intelligence through NeuroAI',2023,'Nature Communications','10.1038/s41467-023-37180-x','Review','Mixed','NeuroAI, embodied Turing test, sensorimotor, next-generation AI, research agenda','Manifesto signed by 27 leading neuro-AI researchers proposing the embodied Turing test as the benchmark for NeuroAI progress.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('NeuroAI and Beyond: Bridging Between Advances in Neuroscience and Artificial Intelligence',2025,'arXiv','10.48550/arXiv.2604.18637','Review','Mixed','NeuroAI, capability gaps, energy efficiency, physical interaction, multi-scale learning','Identifies three fundamental capability gaps in current AI and maps the neuroscience principles that address each, presenting a research roadmap for NeuroAI.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('A Computational Perspective on NeuroAI and Synthetic Biological Intelligence',2025,'arXiv','10.48550/arXiv.2509.23896','Review','Mixed','synthetic biological intelligence, neuromorphic, predictive coding, active inference, brain organoids','Reviews computational frameworks at the neuro-AI interface including predictive coding, active inference, and neuromorphic computing, with attention to emerging synthetic biological intelligence research.');

-- ============================================================
-- END OF PART 1
-- Continue with phase3b_insert_continuation.sql
-- That file begins with the Output & Generation papers (9 papers)
-- ============================================================
