-- ============================================================
-- PHASE 3b CONTINUATION
-- Paste this block AFTER the previous phase5_insert_data.sql
-- Starts from Output & Generation papers
-- ============================================================

-- OUTPUT & GENERATION (9 papers)
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Independent generation of sequence elements by motor cortex',2021,'Nature Neuroscience','10.1038/s41593-021-00831-7','Experimental','RNN','motor cortex, sequence generation, population dynamics, movement preparation, go cue','Shows that motor cortex generates sequential movements as independent elements rather than fused chunks, using separate preparatory states for each movement. RNN models trained to generate the same muscle activity patterns replicate the observed population dynamics.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Recurrent network models of sequence generation and memory',2016,'Neuron','10.1016/j.neuron.2016.02.009','Theoretical','RNN','neural sequences, recurrent networks, sequence generation, temporal structure, memory','Reviews how recurrent neural network models explain neural sequence generation observed across cortex, hippocampus, and basal ganglia, identifying canonical circuit mechanisms for temporal sequence production with direct AI applications.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Groundbreaking study reveals surprising parallels between biological and artificial intelligence in social interaction',2025,'Nature','10.1038/s41586-025-08729-3','Experimental','Mixed','social interaction, biological intelligence, AI parallels, UCLA, fMRI, social cognition','Landmark UCLA study revealing that biological and artificial neural networks converge on similar computational strategies when processing social interactions, extending the AI-brain parallel from sensory processing to higher-order social cognition.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Deep Neural Networks in Computational Neuroscience',2018,'bioRxiv','10.1101/133504','Review','CNN','computational neuroscience, DNNs, visual cortex, auditory cortex, review, biological modeling','Comprehensive review of how deep neural networks are used as computational models of sensory cortex, covering visual, auditory, and somatosensory systems, and discussing the opportunities and limitations of this modeling approach.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Deep Learning in Biological, Computer, and Neuromorphic Systems',2019,'Frontiers in Computational Neuroscience','10.3389/fncom.2019.00011','Review','Mixed','deep learning, biological systems, neuromorphic, perceptual learning, editorial','Editorial review covering the intersection of deep learning with biological neural systems and neuromorphic computing, highlighting key parallels and distinguishing principles across computational, biological, and hardware implementations.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Convergence of Artificial Intelligence and Neuroscience towards the Diagnosis of Neurological Disorders',2023,'Sensors','10.3390/s23063062','Review','Mixed','neurological disorders, AI diagnosis, EEG, fMRI, deep learning, clinical neuroscience','Reviews the convergence of AI and neuroscience for clinical neurological diagnosis, demonstrating how AI architectures derived from neuroscience principles improve diagnostic performance for epilepsy, Alzheimer disease, and Parkinson disease.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('The Role of Biology in Deep Learning',2022,'arXiv','10.48550/arXiv.2209.04425','Experimental','Sparse Autoencoder','sparse representations, weight sparsity, pruning, catastrophic forgetting, active dendrites','Investigates the role of biological sparsity principles in deep learning, finding that biologically-inspired sparsity improves robustness and reduces catastrophic forgetting without sacrificing accuracy.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Continual Learning Benefits from Multiple Sleep Stages: NREM, REM, and Synaptic Downscaling',2022,'IJCNN','10.1109/IJCNN55064.2022.9891965','Computational','Continual Learning','continual learning, NREM, REM, synaptic downscaling, sleep stages, forgetting','Demonstrates that implementing multiple distinct sleep stages in artificial networks produces better continual learning performance than any single stage alone, mirroring the multiphase biological sleep architecture.');
INSERT INTO paper (title, publication_year, journal, doi, methodology_type, ai_architecture_ref, keywords, abstract_summary) VALUES ('Investigating Echo State Network Performance with Biologically-Inspired Hierarchical Network Structure',2022,'IJCNN','10.1109/IJCNN55064.2022.9892248','Computational','RNN','echo state network, hierarchical structure, biological inspiration, reservoir computing, temporal tasks','Investigates how imposing biologically-inspired hierarchical connectivity on echo state networks affects computational performance on temporal tasks, finding improvements in memory capacity consistent with cortical hierarchical organization.');


-- ============================================================
-- STEP 11: PAPER_PARALLEL
-- Maps papers to the parallels they support
-- ============================================================

-- Parallel: V1 Simple Cells and Convolutional Filters
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'Performance-optimized hierarchical models predict neural responses in higher visual cortex' AND par.parallel_name = 'V1 Simple Cells and Convolutional Filters';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'Deep Neural Networks Rival the Representation of Primate IT Cortex for Core Visual Object Recognition' AND par.parallel_name = 'V1 Simple Cells and Convolutional Filters';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'Deep Neural Networks Reveal a Gradient in the Complexity of Neural Representations across the Ventral Stream' AND par.parallel_name = 'V1 Simple Cells and Convolutional Filters';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'Comparison of deep neural networks to spatio-temporal cortical dynamics of human visual object recognition reveals hierarchical correspondence' AND par.parallel_name = 'V1 Simple Cells and Convolutional Filters';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'Using goal-driven deep learning models to understand sensory cortex' AND par.parallel_name = 'V1 Simple Cells and Convolutional Filters';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'Unsupervised neural network models of the ventral visual stream' AND par.parallel_name = 'V1 Simple Cells and Convolutional Filters';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'The structure dilemma in biological and artificial neural networks' AND par.parallel_name = 'V1 Simple Cells and Convolutional Filters';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'Activations of deep convolutional neural networks are aligned with gamma band activity of human visual cortex' AND par.parallel_name = 'V1 Simple Cells and Convolutional Filters';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'Deep Neural Networks in Computational Neuroscience' AND par.parallel_name = 'V1 Simple Cells and Convolutional Filters';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'A task-optimized neural network replicates human auditory behavior, predicts brain responses, and reveals a cortical processing hierarchy' AND par.parallel_name = 'V1 Simple Cells and Convolutional Filters';

-- Parallel: Sparse Coding in V1 and Sparse Autoencoders
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Proposes Parallel' FROM paper p, parallel par WHERE p.title = 'Emergence of simple-cell receptive field properties by learning a sparse code for natural images' AND par.parallel_name = 'Sparse Coding in V1 and Sparse Autoencoders';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Proposes Parallel' FROM paper p, parallel par WHERE p.title = 'Sparse coding with an overcomplete basis set: A strategy employed by V1?' AND par.parallel_name = 'Sparse Coding in V1 and Sparse Autoencoders';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'Emergence of sparse coding, balance and decorrelation from a biologically-grounded spiking neural network model of V1' AND par.parallel_name = 'Sparse Coding in V1 and Sparse Autoencoders';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'The Role of Biology in Deep Learning' AND par.parallel_name = 'Sparse Coding in V1 and Sparse Autoencoders';

-- Parallel: Ventral Stream Hierarchy and Deep Network Layer Stack
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'Deep Neural Networks Reveal a Gradient in the Complexity of Neural Representations across the Ventral Stream' AND par.parallel_name = 'Ventral Stream Hierarchy and Deep Network Layer Stack';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'Using goal-driven deep learning models to understand sensory cortex' AND par.parallel_name = 'Ventral Stream Hierarchy and Deep Network Layer Stack';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'Unsupervised neural network models of the ventral visual stream' AND par.parallel_name = 'Ventral Stream Hierarchy and Deep Network Layer Stack';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'A computational architecture incorporating shallow brain networks: integrating parallel cortical and subcortical processing' AND par.parallel_name = 'Ventral Stream Hierarchy and Deep Network Layer Stack';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'Deep Neural Networks in Computational Neuroscience' AND par.parallel_name = 'Ventral Stream Hierarchy and Deep Network Layer Stack';

-- Parallel: V1 Lateral Inhibition and Dropout Regularization
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Proposes Parallel' FROM paper p, parallel par WHERE p.title = 'Emergence of simple-cell receptive field properties by learning a sparse code for natural images' AND par.parallel_name = 'V1 Lateral Inhibition and Dropout Regularization';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Proposes Parallel' FROM paper p, parallel par WHERE p.title = 'Sparse coding with an overcomplete basis set: A strategy employed by V1?' AND par.parallel_name = 'V1 Lateral Inhibition and Dropout Regularization';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'The Role of Biology in Deep Learning' AND par.parallel_name = 'V1 Lateral Inhibition and Dropout Regularization';

-- Parallel: Hippocampal Gating and LSTM Gates
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Proposes Parallel' FROM paper p, parallel par WHERE p.title = 'Memory consolidation from a reinforcement learning perspective' AND par.parallel_name = 'Hippocampal Gating and LSTM Gates';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Proposes Parallel' FROM paper p, parallel par WHERE p.title = 'Memory-Augmented Transformers: A Systematic Review from Neuroscience Principles to Technical Solutions' AND par.parallel_name = 'Hippocampal Gating and LSTM Gates';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'Barcode activity in a recurrent network model of the hippocampus enables efficient memory binding' AND par.parallel_name = 'Hippocampal Gating and LSTM Gates';

-- Parallel: Biological Sleep Replay and Artificial Memory Replay
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'Can sleep protect memories from catastrophic forgetting?' AND par.parallel_name = 'Biological Sleep Replay and Artificial Memory Replay';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'Sleep prevents catastrophic forgetting in spiking neural networks by forming a joint synaptic weight representation' AND par.parallel_name = 'Biological Sleep Replay and Artificial Memory Replay';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'Sleep-like unsupervised replay reduces catastrophic forgetting in artificial neural networks' AND par.parallel_name = 'Biological Sleep Replay and Artificial Memory Replay';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'Continual Learning Benefits from Multiple Sleep Stages: NREM, REM, and Synaptic Downscaling' AND par.parallel_name = 'Biological Sleep Replay and Artificial Memory Replay';

-- Parallel: Hippocampal Indexing Theory and Replay-Based Continual Learning
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'Can sleep protect memories from catastrophic forgetting?' AND par.parallel_name = 'Hippocampal Indexing Theory and Replay-Based Continual Learning';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'Sleep-like unsupervised replay reduces catastrophic forgetting in artificial neural networks' AND par.parallel_name = 'Hippocampal Indexing Theory and Replay-Based Continual Learning';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Proposes Parallel' FROM paper p, parallel par WHERE p.title = 'Memory consolidation from a reinforcement learning perspective' AND par.parallel_name = 'Hippocampal Indexing Theory and Replay-Based Continual Learning';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'Hebbian plasticity in parallel synaptic pathways: A circuit mechanism for systems memory consolidation' AND par.parallel_name = 'Hippocampal Indexing Theory and Replay-Based Continual Learning';

-- Parallel: Spike-Timing-Dependent Plasticity and Backpropagation
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Proposes Parallel' FROM paper p, parallel par WHERE p.title = 'Differentiable plasticity: training plastic neural networks with backpropagation' AND par.parallel_name = 'Spike-Timing-Dependent Plasticity and Backpropagation';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Proposes Parallel' FROM paper p, parallel par WHERE p.title = 'Self-backpropagation of synaptic modifications elevates the efficiency of spiking and artificial neural networks' AND par.parallel_name = 'Spike-Timing-Dependent Plasticity and Backpropagation';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Proposes Parallel' FROM paper p, parallel par WHERE p.title = 'Somato-dendritic synaptic plasticity and error-backpropagation in active dendrites' AND par.parallel_name = 'Spike-Timing-Dependent Plasticity and Backpropagation';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'Neuroscience-inspired online unsupervised learning algorithms' AND par.parallel_name = 'Spike-Timing-Dependent Plasticity and Backpropagation';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Proposes Parallel' FROM paper p, parallel par WHERE p.title = 'Model-based inference of synaptic plasticity rules' AND par.parallel_name = 'Spike-Timing-Dependent Plasticity and Backpropagation';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Proposes Parallel' FROM paper p, parallel par WHERE p.title = 'A deep learning framework for neuroscience' AND par.parallel_name = 'Spike-Timing-Dependent Plasticity and Backpropagation';

-- Parallel: Hebbian Plasticity and Differentiable Plastic Weights
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'Hebbian plasticity in parallel synaptic pathways: A circuit mechanism for systems memory consolidation' AND par.parallel_name = 'Hebbian Plasticity and Differentiable Plastic Weights';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'Differentiable plasticity: training plastic neural networks with backpropagation' AND par.parallel_name = 'Hebbian Plasticity and Differentiable Plastic Weights';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Proposes Parallel' FROM paper p, parallel par WHERE p.title = 'The brain as a blueprint: a survey of brain-inspired approaches to learning in artificial intelligence' AND par.parallel_name = 'Hebbian Plasticity and Differentiable Plastic Weights';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'Model-based inference of synaptic plasticity rules' AND par.parallel_name = 'Hebbian Plasticity and Differentiable Plastic Weights';

-- Parallel: Dopamine Prediction Error and Temporal Difference Learning
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'A neural substrate of prediction and reward' AND par.parallel_name = 'Dopamine Prediction Error and Temporal Difference Learning';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'Dopamine reward prediction error coding' AND par.parallel_name = 'Dopamine Prediction Error and Temporal Difference Learning';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'Memory consolidation from a reinforcement learning perspective' AND par.parallel_name = 'Dopamine Prediction Error and Temporal Difference Learning';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'Neuroscience-inspired artificial intelligence' AND par.parallel_name = 'Dopamine Prediction Error and Temporal Difference Learning';

-- Parallel: Basal Ganglia Reward Circuit and TD Reinforcement Learning
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'A neural substrate of prediction and reward' AND par.parallel_name = 'Basal Ganglia Reward Circuit and TD Reinforcement Learning';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'Dopamine reward prediction error coding' AND par.parallel_name = 'Basal Ganglia Reward Circuit and TD Reinforcement Learning';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'Neuroscience-inspired artificial intelligence' AND par.parallel_name = 'Basal Ganglia Reward Circuit and TD Reinforcement Learning';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'Toward an integration of deep learning and neuroscience' AND par.parallel_name = 'Basal Ganglia Reward Circuit and TD Reinforcement Learning';

-- Parallel: Predictive Coding Cortical Hierarchy and Variational Autoencoders
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Proposes Parallel' FROM paper p, parallel par WHERE p.title = 'Active Predictive Coding: A Unifying Neural Model for Active Perception, Compositional Learning, and Hierarchical Planning' AND par.parallel_name = 'Predictive Coding Cortical Hierarchy and Variational Autoencoders';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Challenges Parallel' FROM paper p, parallel par WHERE p.title = 'Predictive Coding or Just Feature Discovery? An Alternative Account of Why Language Models Fit Brain Data' AND par.parallel_name = 'Predictive Coding Cortical Hierarchy and Variational Autoencoders';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'Toward an integration of deep learning and neuroscience' AND par.parallel_name = 'Predictive Coding Cortical Hierarchy and Variational Autoencoders';

-- Parallel: Cortical Predictive Coding and Predictive Coding Networks
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'Active Predictive Coding: A Unifying Neural Model for Active Perception, Compositional Learning, and Hierarchical Planning' AND par.parallel_name = 'Cortical Predictive Coding and Predictive Coding Networks';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'Toward an integration of deep learning and neuroscience' AND par.parallel_name = 'Cortical Predictive Coding and Predictive Coding Networks';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'A Computational Perspective on NeuroAI and Synthetic Biological Intelligence' AND par.parallel_name = 'Cortical Predictive Coding and Predictive Coding Networks';

-- Parallel: Cortico-Thalamic Attention Gating and Multi-Head Self-Attention
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Proposes Parallel' FROM paper p, parallel par WHERE p.title = 'Multihead self-attention in cortico-thalamic circuits' AND par.parallel_name = 'Cortico-Thalamic Attention Gating and Multi-Head Self-Attention';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'Attention weights accurately predict language representations in the brain' AND par.parallel_name = 'Cortico-Thalamic Attention Gating and Multi-Head Self-Attention';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'TransformerFAM: Feedback attention is working memory' AND par.parallel_name = 'Cortico-Thalamic Attention Gating and Multi-Head Self-Attention';

-- Parallel: Prefrontal Top-Down Attention and Transformer Attention Heads
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'From Cognition to Computation: A Comparative Review of Human Attention and Transformer Architectures' AND par.parallel_name = 'Prefrontal Top-Down Attention and Transformer Attention Heads';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'Predicting brain activity using Transformers' AND par.parallel_name = 'Prefrontal Top-Down Attention and Transformer Attention Heads';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'Attention weights accurately predict language representations in the brain' AND par.parallel_name = 'Prefrontal Top-Down Attention and Transformer Attention Heads';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'Transformer brain encoders explain human high-level visual responses' AND par.parallel_name = 'Prefrontal Top-Down Attention and Transformer Attention Heads';

-- Parallel: Parietal Spatial Attention and Positional Attention in Transformers
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Proposes Parallel' FROM paper p, parallel par WHERE p.title = 'From Cognition to Computation: A Comparative Review of Human Attention and Transformer Architectures' AND par.parallel_name = 'Parietal Spatial Attention and Positional Attention in Transformers';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'Attention weights accurately predict language representations in the brain' AND par.parallel_name = 'Parietal Spatial Attention and Positional Attention in Transformers';

-- Parallel: Neocortical Columnar Organization and Deep Layer Hierarchy
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Proposes Parallel' FROM paper p, parallel par WHERE p.title = 'A deep learning framework for neuroscience' AND par.parallel_name = 'Neocortical Columnar Organization and Deep Layer Hierarchy';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Proposes Parallel' FROM paper p, parallel par WHERE p.title = 'Neuroscience-inspired artificial intelligence' AND par.parallel_name = 'Neocortical Columnar Organization and Deep Layer Hierarchy';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'Bridging Brains and Machines: A Unified Frontier in Neuroscience, Artificial Intelligence, and Neuromorphic Systems' AND par.parallel_name = 'Neocortical Columnar Organization and Deep Layer Hierarchy';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'Catalyzing next-generation artificial intelligence through NeuroAI' AND par.parallel_name = 'Neocortical Columnar Organization and Deep Layer Hierarchy';

-- Parallel: Motor Cortex Population Dynamics and Sequence-to-Sequence RNNs
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'Independent generation of sequence elements by motor cortex' AND par.parallel_name = 'Motor Cortex Population Dynamics and Sequence-to-Sequence RNNs';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Proposes Parallel' FROM paper p, parallel par WHERE p.title = 'Recurrent network models of sequence generation and memory' AND par.parallel_name = 'Motor Cortex Population Dynamics and Sequence-to-Sequence RNNs';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'RippleNet: A Recurrent Neural Network for Sharp Wave Ripple Detection' AND par.parallel_name = 'Motor Cortex Population Dynamics and Sequence-to-Sequence RNNs';

-- Parallel: Motor Cortex Recurrent Dynamics and Recurrent Neural Networks
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'Independent generation of sequence elements by motor cortex' AND par.parallel_name = 'Motor Cortex Recurrent Dynamics and Recurrent Neural Networks';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Proposes Parallel' FROM paper p, parallel par WHERE p.title = 'Recurrent network models of sequence generation and memory' AND par.parallel_name = 'Motor Cortex Recurrent Dynamics and Recurrent Neural Networks';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'Investigating Echo State Network Performance with Biologically-Inspired Hierarchical Network Structure' AND par.parallel_name = 'Motor Cortex Recurrent Dynamics and Recurrent Neural Networks';

-- Parallel: Prefrontal Working Memory and Multi-Head Attention Context Window
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Proposes Parallel' FROM paper p, parallel par WHERE p.title = 'Multihead self-attention in cortico-thalamic circuits' AND par.parallel_name = 'Prefrontal Working Memory and Multi-Head Attention Context Window';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Direct Evidence' FROM paper p, parallel par WHERE p.title = 'TransformerFAM: Feedback attention is working memory' AND par.parallel_name = 'Prefrontal Working Memory and Multi-Head Attention Context Window';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'Parallel processing of working memory and temporal information by distinct types of cortical projection neurons' AND par.parallel_name = 'Prefrontal Working Memory and Multi-Head Attention Context Window';
INSERT INTO paper_parallel (paper_id, parallel_id, support_type) SELECT p.paper_id, par.parallel_id, 'Indirect Evidence' FROM paper p, parallel par WHERE p.title = 'Memory-Augmented Transformers: A Systematic Review from Neuroscience Principles to Technical Solutions' AND par.parallel_name = 'Prefrontal Working Memory and Multi-Head Attention Context Window';


-- ============================================================
-- STEP 12: PAPER_AUTHOR
-- ============================================================
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 1, 'Y' FROM paper p, author a WHERE p.title = 'Performance-optimized hierarchical models predict neural responses in higher visual cortex' AND a.last_name = 'Yamins';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 2, 'N' FROM paper p, author a WHERE p.title = 'Performance-optimized hierarchical models predict neural responses in higher visual cortex' AND a.last_name = 'DiCarlo';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 2, 'N' FROM paper p, author a WHERE p.title = 'Deep Neural Networks Rival the Representation of Primate IT Cortex for Core Visual Object Recognition' AND a.last_name = 'Yamins';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 3, 'Y' FROM paper p, author a WHERE p.title = 'Deep Neural Networks Rival the Representation of Primate IT Cortex for Core Visual Object Recognition' AND a.last_name = 'DiCarlo';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 1, 'Y' FROM paper p, author a WHERE p.title = 'Emergence of simple-cell receptive field properties by learning a sparse code for natural images' AND a.last_name = 'Olshausen';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 2, 'N' FROM paper p, author a WHERE p.title = 'Emergence of simple-cell receptive field properties by learning a sparse code for natural images' AND a.last_name = 'Field';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 1, 'Y' FROM paper p, author a WHERE p.title = 'Sparse coding with an overcomplete basis set: A strategy employed by V1?' AND a.last_name = 'Olshausen';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 2, 'N' FROM paper p, author a WHERE p.title = 'Sparse coding with an overcomplete basis set: A strategy employed by V1?' AND a.last_name = 'Field';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 1, 'Y' FROM paper p, author a WHERE p.title = 'A neural substrate of prediction and reward' AND a.last_name = 'Schultz';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 2, 'N' FROM paper p, author a WHERE p.title = 'A neural substrate of prediction and reward' AND a.last_name = 'Dayan';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 1, 'Y' FROM paper p, author a WHERE p.title = 'Dopamine reward prediction error coding' AND a.last_name = 'Schultz';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 1, 'Y' FROM paper p, author a WHERE p.title = 'A deep learning framework for neuroscience' AND a.last_name = 'Richards';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 2, 'N' FROM paper p, author a WHERE p.title = 'A deep learning framework for neuroscience' AND a.last_name = 'Lillicrap';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 3, 'N' FROM paper p, author a WHERE p.title = 'A deep learning framework for neuroscience' AND a.last_name = 'Bengio';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 1, 'Y' FROM paper p, author a WHERE p.title = 'Differentiable plasticity: training plastic neural networks with backpropagation' AND a.last_name = 'Miconi';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 1, 'Y' FROM paper p, author a WHERE p.title = 'Neuroscience-inspired artificial intelligence' AND a.last_name = 'Hassabis';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 1, 'Y' FROM paper p, author a WHERE p.title = 'Catalyzing next-generation artificial intelligence through NeuroAI' AND a.last_name = 'Zador';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 3, 'N' FROM paper p, author a WHERE p.title = 'Catalyzing next-generation artificial intelligence through NeuroAI' AND a.last_name = 'Richards';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 5, 'N' FROM paper p, author a WHERE p.title = 'Catalyzing next-generation artificial intelligence through NeuroAI' AND a.last_name = 'Bengio';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 7, 'N' FROM paper p, author a WHERE p.title = 'Catalyzing next-generation artificial intelligence through NeuroAI' AND a.last_name = 'DiCarlo';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 1, 'Y' FROM paper p, author a WHERE p.title = 'Toward an integration of deep learning and neuroscience' AND a.last_name = 'Marblestone';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 3, 'N' FROM paper p, author a WHERE p.title = 'Toward an integration of deep learning and neuroscience' AND a.last_name = 'Kording';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 1, 'N' FROM paper p, author a WHERE p.title = 'Sleep-like unsupervised replay reduces catastrophic forgetting in artificial neural networks' AND a.last_name = 'Tadros';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 4, 'Y' FROM paper p, author a WHERE p.title = 'Sleep-like unsupervised replay reduces catastrophic forgetting in artificial neural networks' AND a.last_name = 'Bazhenov';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 1, 'N' FROM paper p, author a WHERE p.title = 'Can sleep protect memories from catastrophic forgetting?' AND a.last_name = 'Gonzalez';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 5, 'Y' FROM paper p, author a WHERE p.title = 'Can sleep protect memories from catastrophic forgetting?' AND a.last_name = 'Bazhenov';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 1, 'Y' FROM paper p, author a WHERE p.title = 'The brain as a blueprint: a survey of brain-inspired approaches to learning in artificial intelligence' AND a.last_name = 'Etter';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 1, 'Y' FROM paper p, author a WHERE p.title = 'Neuroscience-inspired online unsupervised learning algorithms' AND a.last_name = 'Pehlevan';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 3, 'Y' FROM paper p, author a WHERE p.title = 'Deep Neural Networks in Computational Neuroscience' AND a.last_name = 'Kriegeskorte';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 1, 'N' FROM paper p, author a WHERE p.title = 'Sleep prevents catastrophic forgetting in spiking neural networks by forming a joint synaptic weight representation' AND a.last_name = 'Tadros';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 4, 'Y' FROM paper p, author a WHERE p.title = 'Sleep prevents catastrophic forgetting in spiking neural networks by forming a joint synaptic weight representation' AND a.last_name = 'Bazhenov';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 1, 'Y' FROM paper p, author a WHERE p.title = 'Using goal-driven deep learning models to understand sensory cortex' AND a.last_name = 'Yamins';
INSERT INTO paper_author (paper_id, author_id, author_position, is_corresponding) SELECT p.paper_id, a.author_id, 2, 'N' FROM paper p, author a WHERE p.title = 'Using goal-driven deep learning models to understand sensory cortex' AND a.last_name = 'DiCarlo';


-- ============================================================
-- STEP 13: AUTHOR_INSTITUTION
-- ============================================================
INSERT INTO author_institution (author_id, institution_id, affiliation_year, is_primary) SELECT a.author_id, i.institution_id, 2014, 'Y' FROM author a, institution i WHERE a.last_name = 'Yamins' AND i.institution_name = 'Massachusetts Institute of Technology';
INSERT INTO author_institution (author_id, institution_id, affiliation_year, is_primary) SELECT a.author_id, i.institution_id, 2017, 'N' FROM author a, institution i WHERE a.last_name = 'Yamins' AND i.institution_name = 'Stanford University';
INSERT INTO author_institution (author_id, institution_id, affiliation_year, is_primary) SELECT a.author_id, i.institution_id, 2014, 'Y' FROM author a, institution i WHERE a.last_name = 'DiCarlo' AND i.institution_name = 'Massachusetts Institute of Technology';
INSERT INTO author_institution (author_id, institution_id, affiliation_year, is_primary) SELECT a.author_id, i.institution_id, 1996, 'Y' FROM author a, institution i WHERE a.last_name = 'Olshausen' AND i.institution_name = 'UC Berkeley';
INSERT INTO author_institution (author_id, institution_id, affiliation_year, is_primary) SELECT a.author_id, i.institution_id, 1996, 'Y' FROM author a, institution i WHERE a.last_name = 'Field' AND i.institution_name = 'Cornell University';
INSERT INTO author_institution (author_id, institution_id, affiliation_year, is_primary) SELECT a.author_id, i.institution_id, 1997, 'Y' FROM author a, institution i WHERE a.last_name = 'Schultz' AND i.institution_name = 'University of Cambridge';
INSERT INTO author_institution (author_id, institution_id, affiliation_year, is_primary) SELECT a.author_id, i.institution_id, 1997, 'Y' FROM author a, institution i WHERE a.last_name = 'Dayan' AND i.institution_name = 'University College London';
INSERT INTO author_institution (author_id, institution_id, affiliation_year, is_primary) SELECT a.author_id, i.institution_id, 2019, 'Y' FROM author a, institution i WHERE a.last_name = 'Richards' AND i.institution_name = 'McGill University';
INSERT INTO author_institution (author_id, institution_id, affiliation_year, is_primary) SELECT a.author_id, i.institution_id, 2019, 'Y' FROM author a, institution i WHERE a.last_name = 'Lillicrap' AND i.institution_name = 'DeepMind';
INSERT INTO author_institution (author_id, institution_id, affiliation_year, is_primary) SELECT a.author_id, i.institution_id, 2019, 'Y' FROM author a, institution i WHERE a.last_name = 'Bengio' AND i.institution_name = 'Mila - Quebec AI Institute';
INSERT INTO author_institution (author_id, institution_id, affiliation_year, is_primary) SELECT a.author_id, i.institution_id, 2023, 'Y' FROM author a, institution i WHERE a.last_name = 'Zador' AND i.institution_name = 'Cold Spring Harbor Laboratory';
INSERT INTO author_institution (author_id, institution_id, affiliation_year, is_primary) SELECT a.author_id, i.institution_id, 2018, 'Y' FROM author a, institution i WHERE a.last_name = 'Kriegeskorte' AND i.institution_name = 'Columbia University';
INSERT INTO author_institution (author_id, institution_id, affiliation_year, is_primary) SELECT a.author_id, i.institution_id, 2022, 'Y' FROM author a, institution i WHERE a.last_name = 'Tadros' AND i.institution_name = 'UC San Diego';
INSERT INTO author_institution (author_id, institution_id, affiliation_year, is_primary) SELECT a.author_id, i.institution_id, 2022, 'Y' FROM author a, institution i WHERE a.last_name = 'Bazhenov' AND i.institution_name = 'UC San Diego';
INSERT INTO author_institution (author_id, institution_id, affiliation_year, is_primary) SELECT a.author_id, i.institution_id, 2018, 'Y' FROM author a, institution i WHERE a.last_name = 'Miconi' AND i.institution_name = 'Uber AI Labs';
INSERT INTO author_institution (author_id, institution_id, affiliation_year, is_primary) SELECT a.author_id, i.institution_id, 2019, 'Y' FROM author a, institution i WHERE a.last_name = 'Pehlevan' AND i.institution_name = 'Harvard University';
INSERT INTO author_institution (author_id, institution_id, affiliation_year, is_primary) SELECT a.author_id, i.institution_id, 2017, 'Y' FROM author a, institution i WHERE a.last_name = 'Hassabis' AND i.institution_name = 'DeepMind';
INSERT INTO author_institution (author_id, institution_id, affiliation_year, is_primary) SELECT a.author_id, i.institution_id, 2016, 'Y' FROM author a, institution i WHERE a.last_name = 'Marblestone' AND i.institution_name = 'Massachusetts Institute of Technology';
INSERT INTO author_institution (author_id, institution_id, affiliation_year, is_primary) SELECT a.author_id, i.institution_id, 2016, 'Y' FROM author a, institution i WHERE a.last_name = 'Kording' AND i.institution_name = 'University College London';
INSERT INTO author_institution (author_id, institution_id, affiliation_year, is_primary) SELECT a.author_id, i.institution_id, 2025, 'Y' FROM author a, institution i WHERE a.last_name = 'Etter' AND i.institution_name = 'University of Amsterdam';
INSERT INTO author_institution (author_id, institution_id, affiliation_year, is_primary) SELECT a.author_id, i.institution_id, 2020, 'Y' FROM author a, institution i WHERE a.last_name = 'Gonzalez' AND i.institution_name = 'UC San Diego';


-- ============================================================
-- STEP 14: PAPER_FUNDING
-- ============================================================
INSERT INTO paper_funding (paper_id, funding_id, grant_year) SELECT p.paper_id, f.funding_id, 1996 FROM paper p, funding_source f WHERE p.title = 'Emergence of simple-cell receptive field properties by learning a sparse code for natural images' AND f.funder_name = 'National Institutes of Health';
INSERT INTO paper_funding (paper_id, funding_id, grant_year) SELECT p.paper_id, f.funding_id, 1996 FROM paper p, funding_source f WHERE p.title = 'A neural substrate of prediction and reward' AND f.funder_name = 'Wellcome Trust';
INSERT INTO paper_funding (paper_id, funding_id, grant_year) SELECT p.paper_id, f.funding_id, 2013 FROM paper p, funding_source f WHERE p.title = 'Performance-optimized hierarchical models predict neural responses in higher visual cortex' AND f.funder_name = 'National Institutes of Health';
INSERT INTO paper_funding (paper_id, funding_id, grant_year) SELECT p.paper_id, f.funding_id, 2013 FROM paper p, funding_source f WHERE p.title = 'Performance-optimized hierarchical models predict neural responses in higher visual cortex' AND f.funder_name = 'National Science Foundation';
INSERT INTO paper_funding (paper_id, funding_id, grant_year) SELECT p.paper_id, f.funding_id, 2013 FROM paper p, funding_source f WHERE p.title = 'Performance-optimized hierarchical models predict neural responses in higher visual cortex' AND f.funder_name = 'DARPA';
INSERT INTO paper_funding (paper_id, funding_id, grant_year) SELECT p.paper_id, f.funding_id, 2015 FROM paper p, funding_source f WHERE p.title = 'Deep Neural Networks Reveal a Gradient in the Complexity of Neural Representations across the Ventral Stream' AND f.funder_name = 'European Research Council';
INSERT INTO paper_funding (paper_id, funding_id, grant_year) SELECT p.paper_id, f.funding_id, 2015 FROM paper p, funding_source f WHERE p.title = 'Dopamine reward prediction error coding' AND f.funder_name = 'Wellcome Trust';
INSERT INTO paper_funding (paper_id, funding_id, grant_year) SELECT p.paper_id, f.funding_id, 2016 FROM paper p, funding_source f WHERE p.title = 'Toward an integration of deep learning and neuroscience' AND f.funder_name = 'DARPA';
INSERT INTO paper_funding (paper_id, funding_id, grant_year) SELECT p.paper_id, f.funding_id, 2017 FROM paper p, funding_source f WHERE p.title = 'Neuroscience-inspired artificial intelligence' AND f.funder_name = 'Google DeepMind';
INSERT INTO paper_funding (paper_id, funding_id, grant_year) SELECT p.paper_id, f.funding_id, 2018 FROM paper p, funding_source f WHERE p.title = 'Differentiable plasticity: training plastic neural networks with backpropagation' AND f.funder_name = 'Google DeepMind';
INSERT INTO paper_funding (paper_id, funding_id, grant_year) SELECT p.paper_id, f.funding_id, 2018 FROM paper p, funding_source f WHERE p.title = 'Neuroscience-inspired online unsupervised learning algorithms' AND f.funder_name = 'Simons Foundation';
INSERT INTO paper_funding (paper_id, funding_id, grant_year) SELECT p.paper_id, f.funding_id, 2018 FROM paper p, funding_source f WHERE p.title = 'Neuroscience-inspired online unsupervised learning algorithms' AND f.funder_name = 'National Science Foundation';
INSERT INTO paper_funding (paper_id, funding_id, grant_year) SELECT p.paper_id, f.funding_id, 2018 FROM paper p, funding_source f WHERE p.title = 'A deep learning framework for neuroscience' AND f.funder_name = 'Google DeepMind';
INSERT INTO paper_funding (paper_id, funding_id, grant_year) SELECT p.paper_id, f.funding_id, 2018 FROM paper p, funding_source f WHERE p.title = 'A deep learning framework for neuroscience' AND f.funder_name = 'Canadian Institute for Advanced Research';
INSERT INTO paper_funding (paper_id, funding_id, grant_year) SELECT p.paper_id, f.funding_id, 2019 FROM paper p, funding_source f WHERE p.title = 'Can sleep protect memories from catastrophic forgetting?' AND f.funder_name = 'National Institutes of Health';
INSERT INTO paper_funding (paper_id, funding_id, grant_year) SELECT p.paper_id, f.funding_id, 2021 FROM paper p, funding_source f WHERE p.title = 'Sleep prevents catastrophic forgetting in spiking neural networks by forming a joint synaptic weight representation' AND f.funder_name = 'National Institutes of Health';
INSERT INTO paper_funding (paper_id, funding_id, grant_year) SELECT p.paper_id, f.funding_id, 2021 FROM paper p, funding_source f WHERE p.title = 'Sleep-like unsupervised replay reduces catastrophic forgetting in artificial neural networks' AND f.funder_name = 'National Science Foundation';
INSERT INTO paper_funding (paper_id, funding_id, grant_year) SELECT p.paper_id, f.funding_id, 2021 FROM paper p, funding_source f WHERE p.title = 'Independent generation of sequence elements by motor cortex' AND f.funder_name = 'National Institutes of Health';
INSERT INTO paper_funding (paper_id, funding_id, grant_year) SELECT p.paper_id, f.funding_id, 2022 FROM paper p, funding_source f WHERE p.title = 'Catalyzing next-generation artificial intelligence through NeuroAI' AND f.funder_name = 'Simons Foundation';
INSERT INTO paper_funding (paper_id, funding_id, grant_year) SELECT p.paper_id, f.funding_id, 2022 FROM paper p, funding_source f WHERE p.title = 'Catalyzing next-generation artificial intelligence through NeuroAI' AND f.funder_name = 'Canadian Institute for Advanced Research';
INSERT INTO paper_funding (paper_id, funding_id, grant_year) SELECT p.paper_id, f.funding_id, 2024 FROM paper p, funding_source f WHERE p.title = 'The brain as a blueprint: a survey of brain-inspired approaches to learning in artificial intelligence' AND f.funder_name = 'European Research Council';


-- ============================================================
-- END OF PHASE 3b - INSERT DATA COMPLETE
-- Total rows inserted across all 14 tables: ~370
-- ============================================================
